apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: bedrock-chat-v2  # CORRECTED: Back to original
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup
            image: mysql:8.0
            command:
            - /bin/bash
            - -c
            - |
              DATE=$(date +%Y%m%d_%H%M%S)
              mysqldump -h mysql -uroot -p$MYSQL_ROOT_PASSWORD bedrock_chat > /backup/backup_${DATE}.sql
              echo "Backup completed: backup_${DATE}.sql"
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
          restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: bedrock-chat-v2  # CORRECTED
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
