# MySQL Persistent Volume
apiVersion: v1
kind: PersistentVolume  
metadata:
  name: mysql-pv
  labels:
    app: bedrock-chat
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/lib/mysql-data
    type: DirectoryOrCreate
