apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-uploads-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/lib/bedrock-files
    type: DirectoryOrCreate