apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: bedrock-chat-v2
data:
  init.sql: |
    -- Create database if not exists
    CREATE DATABASE IF NOT EXISTS bedrock_chat;
    USE bedrock_chat;
    
    -- Create user if not exists
    CREATE USER IF NOT EXISTS 'bedrock_user'@'%' IDENTIFIED BY 'bedrock_password';
    GRANT ALL PRIVILEGES ON bedrock_chat.* TO 'bedrock_user'@'%';
    FLUSH PRIVILEGES;
    
    -- Create conversations table
    CREATE TABLE IF NOT EXISTS conversations (
        id INT AUTO_INCREMENT PRIMARY KEY,
        session_id VARCHAR(255) NOT NULL,
        message TEXT NOT NULL,
        response TEXT NOT NULL,
        model_used VARCHAR(100),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_session_id (session_id),
        INDEX idx_created_at (created_at)
    );
    
    -- Create file_uploads table for file service
    CREATE TABLE IF NOT EXISTS file_uploads (
        id INT AUTO_INCREMENT PRIMARY KEY,
        session_id VARCHAR(255) NOT NULL,
        filename VARCHAR(255) NOT NULL,
        original_name VARCHAR(255) NOT NULL,
        file_path TEXT NOT NULL,
        content_type VARCHAR(100),
        file_size BIGINT,
        content TEXT,
        has_text BOOLEAN DEFAULT FALSE,
        upload_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_session_id (session_id),
        INDEX idx_filename (filename),
        INDEX idx_upload_timestamp (upload_timestamp)
    );
    
    -- Insert initial test data
    INSERT IGNORE INTO conversations (session_id, message, response, model_used) VALUES 
    ('init-session', 'System initialization', 'Database initialized successfully', 'system');
