apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: bedrock-chat
  labels:
    app: mysql
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        args:
        - --default-authentication-plugin=mysql_native_password
        - --innodb-buffer-pool-size=512M
        - --max-connections=200
        - --innodb-log-file-size=128M
        - --innodb-buffer-pool-instances=2
        - --innodb-flush-log-at-trx-commit=2
        - --sync-binlog=0
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - 'mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}'
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 20
          timeoutSeconds: 10
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - 'mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}'
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - 'mysql -h localhost -u root -p${MYSQL_ROOT_PASSWORD} -e "SELECT 1"'
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: init-script
        configMap:
          name: mysql-init-script
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 20Gi
