# k8s/pvc/file-uploads-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-uploads-pvc
  namespace: bedrock-chat-v2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage  # Add this line
  resources:
    requests:
      storage: 20Gi
