# k8s/statefulsets/mysql-statefulset-fixed.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: bedrock-chat-v2
  labels:
    app: mysql
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        args:
        - --default-authentication-plugin=mysql_native_password
        - --innodb-buffer-pool-size=128M
        - --max-connections=100
        - --skip-name-resolve
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - 'mysqladmin ping -h localhost -u root -p"$MYSQL_ROOT_PASSWORD"'
          initialDelaySeconds: 60  # Increased from 30
          periodSeconds: 15        # Increased from 10
          timeoutSeconds: 10       # Increased from 5
          successThreshold: 1
          failureThreshold: 20     # Increased from 15
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - 'mysqladmin ping -h localhost -u root -p"$MYSQL_ROOT_PASSWORD"'
          initialDelaySeconds: 120  # Increased from 60
          periodSeconds: 30         # Increased from 20
          timeoutSeconds: 10        # Increased from 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - 'mysql -h localhost -u root -p"$MYSQL_ROOT_PASSWORD" -e "SELECT 1"'
          initialDelaySeconds: 90   # Increased from 45
          periodSeconds: 15         # Increased from 10
          timeoutSeconds: 10        # Increased from 5
          successThreshold: 1
          failureThreshold: 5       # Increased from 3
        resources:
          requests:
            memory: "512Mi"   # Increased from 256Mi
            cpu: "200m"       # Increased from 100m
          limits:
            memory: "2Gi"     # Increased from 1Gi
            cpu: "1000m"      # Increased from 500m
      volumes:
      - name: init-script
        configMap:
          name: mysql-init-script
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-storage
      resources:
        requests:
          storage: 10Gi
